

all:
#	gcc -g -o program dSFMT.c cell.c main.c -lm
	gcc -O3 -o program dSFMT.c cell.c main.c -lm -ffast-math
#	gcc -pg -o program dSFMT.c cell.c main.c -lm -ffast-math -mrecip

clean:
	rm *.o program
